server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agendador
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
